/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface GthmbNoiseyNode {
    /**
    * The level of the noise!
    */
    'noiseLevel': number;
  }
  interface ImgBrightness {}
}

declare global {


  interface HTMLGthmbNoiseyNodeElement extends Components.GthmbNoiseyNode, HTMLStencilElement {}
  var HTMLGthmbNoiseyNodeElement: {
    prototype: HTMLGthmbNoiseyNodeElement;
    new (): HTMLGthmbNoiseyNodeElement;
  };

  interface HTMLImgBrightnessElement extends Components.ImgBrightness, HTMLStencilElement {}
  var HTMLImgBrightnessElement: {
    prototype: HTMLImgBrightnessElement;
    new (): HTMLImgBrightnessElement;
  };
  interface HTMLElementTagNameMap {
    'gthmb-noisey-node': HTMLGthmbNoiseyNodeElement;
    'img-brightness': HTMLImgBrightnessElement;
  }
}

declare namespace LocalJSX {
  interface GthmbNoiseyNode extends JSXBase.HTMLAttributes<HTMLGthmbNoiseyNodeElement> {
    /**
    * The level of the noise!
    */
    'noiseLevel'?: number;
  }
  interface ImgBrightness extends JSXBase.HTMLAttributes<HTMLImgBrightnessElement> {}

  interface IntrinsicElements {
    'gthmb-noisey-node': GthmbNoiseyNode;
    'img-brightness': ImgBrightness;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


